-- Archiving changelog
USE history_data;

CREATE TABLE T_SPX (
        ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        DATE DATE NOT NULL,
        OPEN DECIMAL(10, 2) NOT NULL,
        HIGH DECIMAL(10, 2) NOT NULL,
        LOW DECIMAL(10,2) NOT NULL,
        CLOSE DECIMAL(10,2) NOT NULL,
        VOLUME BIGINT NOT NULL,
        UNIQUE(DATE)
);

CREATE TABLE T_NDQ (
        ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        DATE DATE NOT NULL,
        OPEN DECIMAL(10, 2) NOT NULL,
        HIGH DECIMAL(10, 2) NOT NULL,
        LOW DECIMAL(10,2) NOT NULL,
        CLOSE DECIMAL(10,2) NOT NULL,
        VOLUME BIGINT NOT NULL,
        UNIQUE(DATE)
);
